### ISSUE TITLE
Change README AND ROAPMAP

### ISSUE THREAD

**Issue by llllOllOOll** [ravencodde/ameiva#1]
Now Ameiva is public and I would like to documentation it. When you have time, chance the README and ROADMAP. @ToniCalfim

**Comment by ToniCalfim** [comment]
Sure.

README file is pretty cool, you only need to change the name of the project.

**Comment by ToniCalfim** [comment]
Also, just tell me more or less what you want ROADMAP to contain. We can chat live or you can send me a Portuguese version via some electronic messenger.
